spring:
  application:
    name: tp-app

  flyway:
    enabled: false
    validate-migration-naming: true
    out-of-order: false

  modulith:
    detection-strategy: explicitly-annotated

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate