package io.teampulse.administration.application.error;

public enum PlatformAdministrationErrorCode {
    ORGANIZATION_DATA_INVALID,
    ORGANIZATION_PROVISIONING_FAILED,
    ORGANIZATION_MUST_REMAIN_CREATING,
    USER_DATA_INVALID,
    USER_EMAIL_ALREADY_USED,
    USER_NOT_FOUND,
    USER_TRANSITION_NOT_ALLOWED,
    USER_LIFECYCLE_FAILED,
    USER_HAS_ACTIVE_RESPONSIBILITIES,
    RESPONSIBILITY_CHECK_UNAVAILABLE
}
