package io.teampulse.organization.domain.organization.error;

public enum OrganizationErrorCode {
    NOT_FOUND,
    INVALID_NAME,
    INVALID_TIMEZONE,
    INVALID_STATUS_TRANSITION,
    ACTIVATION_REQUIREMENTS_NOT_MET,
    ADMINISTRATOR_NOT_FOUND,
    ADMINISTRATOR_NOT_AVAILABLE,
    MANAGER_NOT_FOUND,
    MANAGER_NOT_AVAILABLE,
    USER_DIRECTORY_UNAVAILABLE,
    REFERENCE_GENERATION_FAILED,
    CONCURRENT_MODIFICATION
}
