package io.teampulse.team.domain.team.error;

public enum TeamErrorCode {
    NOT_FOUND,
    INVALID_NAME,
    ORGANIZATION_NOT_FOUND,
    ORGANIZATION_UNAVAILABLE,
    ORGANIZATION_DIRECTORY_UNAVAILABLE,
    ADMINISTRATOR_NOT_FOUND,
    ADMINISTRATOR_NOT_AVAILABLE,
    MANAGER_NOT_FOUND,
    MANAGER_NOT_AVAILABLE,
    USER_DIRECTORY_UNAVAILABLE,
    INVALID_STATUS_TRANSITION,
    TEAM_UNAVAILABLE,
    MEMBER_NOT_FOUND,
    MEMBER_ALREADY_EXISTS,
    MEMBER_USER_NOT_FOUND,
    MEMBER_USER_NOT_AVAILABLE,
    INVALID_MEMBER_STATUS_TRANSITION,
    REFERENCE_GENERATION_FAILED,
    CONCURRENT_MODIFICATION
}
